# Generated by Django 3.0.7 on 2020-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0003_auto_20200624_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(default='pics/default.jpg', upload_to='pics'),
        ),
    ]
