# Generated by Django 3.0.7 on 2020-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0005_testsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
