# Generated by Django 3.0.7 on 2020-08-25 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0006_testresult_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='is_correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
